#!/bin/bash

set -eu -o pipefail
cd "`dirname $0`"
export JULIA_PROJECT=~+
cd ..
set +euv +o pipefail
. cset/bin/activate
set -euv -o pipefail
echo $JULIA_PROJECT
exec setarch -R julia-1.5.3/bin/julia run_base_ci.jl \
    2> >(exec setsid -w tee -a run_base_ci.stderr) \
    1> >(exec setsid -w tee -a run_base_ci.stdout)
