#!/bin/bash

set -eux -o pipefail
cd "`dirname $0`"
export JULIA_PROJECT=~+
cd ..
echo $JULIA_PROJECT
exec sudo -u nanosoldier --preserve-env=JULIA_PROJECT \
    setarch -R julia-1.6.6/bin/julia run_base_ci.jl \
    2> >(umask 007 && exec sudo -u nanosoldier setsid -w tee -a run_base_ci.stderr) \
    1> >(umask 007 && exec sudo -u nanosoldier setsid -w tee -a run_base_ci.stdout)
