name: CI
on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4

      - name: "Allow unprivileged user namespaces"
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      # install Julia
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      # set-up packages
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1

      - uses: julia-actions/julia-runtest@v1
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: uploads-to-NanosoldierReports
          path: /home/runner/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/NanosoldierReports/pkgeval/by_hash/redacted_vs_redacted/
